# Generated by Django 6.0.7 on 2026-07-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_copies',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='total_copies',
            field=models.IntegerField(default=1),
        ),
    ]
