# Generated by Django 6.0.7 on 2026-07-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fine_paid',
            field=models.BooleanField(default=False),
        ),
    ]
